### ISSUE TITLE
Auto-scroll down to green card process when `擲杯` is triggered

### ISSUE THREAD

**Issue by wingchen** [qq830214a/bobigreencard#3]
Currently, when `擲杯` is done and the result is rendered out, we do not auto-scroll users to their green card processes part. Let's change it.

Accepting Criteria:
- When `擲杯` is triggered and the result is rendered out, auto-scroll down to green card process part.

**Comment by larrychen-ca** [comment]
@wingchen Please verify on the latest master branch and close this issue after verification.
